# Generated by Django 3.2.7 on 2021-09-20 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True, verbose_name='ид стим')),
                ('name', models.CharField(max_length=5000, verbose_name='Название')),
                ('isExclusive', models.BooleanField(verbose_name='эксклюзив для ps')),
                ('isFree', models.BooleanField(verbose_name='бесплатно')),
                ('date_add', models.DateTimeField(default=datetime.datetime(2021, 9, 20, 19, 53, 28, 935498, tzinfo=utc), verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'g_game',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'db_table': 'g_status',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TypePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Платформа',
                'db_table': 'g_platform',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'db_table': 'g_type',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UpsellServiceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Название')),
                ('sale_text', models.CharField(max_length=100)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2021, 9, 20, 19, 53, 28, 936475, tzinfo=utc), verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.product')),
            ],
            options={
                'verbose_name': 'Скидка по подписке',
                'db_table': 'g_UpsellServiceBranding',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.typeplatform'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.status'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.typeproduct'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.CharField(max_length=50)),
                ('discountText', models.CharField(max_length=50, null=True)),
                ('discountedPrice', models.CharField(max_length=50, null=True)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2021, 9, 20, 19, 53, 28, 939404, tzinfo=utc), verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.product')),
            ],
            options={
                'verbose_name': 'Цены',
                'db_table': 'g_price',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('date_add', models.DateTimeField(default=datetime.datetime(2021, 9, 20, 19, 53, 28, 938427, tzinfo=utc), verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.product')),
            ],
            options={
                'verbose_name': 'Медиа',
                'db_table': 'g_medis',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
