# Generated by Django 3.2.7 on 2021-09-23 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='platform',
        ),
        migrations.AlterField(
            model_name='media',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 9, 48, 13, 495649, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 9, 48, 13, 495649, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 9, 48, 13, 480023, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='upsellservicebranding',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 9, 48, 13, 495649, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_helper.typeplatform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.product')),
            ],
            options={
                'verbose_name': 'Платформа игры',
                'db_table': 'g_product_platform',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('product', 'platform')},
            },
        ),
    ]
