# Generated by Django 3.2.7 on 2021-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0003_auto_20210926_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
