# Generated by Django 3.2.7 on 2021-09-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0004_alter_media_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upsellservicebranding',
            unique_together={('product', 'type', 'sale_text')},
        ),
    ]
