# Generated by Django 3.2.7 on 2021-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0006_auto_20211010_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsellservicebranding',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
