# Generated by Django 3.2.7 on 2021-10-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0008_alter_upsellservicebranding_date_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUpsellServiceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подписка',
                'db_table': 'g_upsell_service_branding',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='upsellservicebranding',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.typeupsellservicebranding'),
        ),
    ]
