# Generated by Django 3.2.7 on 2021-10-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0009_auto_20211010_1803'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeupsellservicebranding',
            table='g_type_upsell_service_branding',
        ),
    ]
