# Generated by Django 3.2.7 on 2021-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0010_alter_typeupsellservicebranding_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_amount',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
