# Generated by Django 3.2.7 on 2021-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0011_price_price_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount_price_amount',
            field=models.IntegerField(null=True, verbose_name='Цена со скидкой'),
        ),
    ]
