# Generated by Django 3.2.7 on 2021-10-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0012_price_discount_price_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'price_amount', 'discount_price_amount')},
        ),
    ]
