# Generated by Django 3.2.7 on 2021-10-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_helper', '0013_alter_price_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_branding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ps_helper.typeupsellservicebranding'),
        ),
    ]
